# Site settings
title: VM Blog
author: Vitor Mussatto
lang: en_US
image:  /favicon.ico
type: blog
tagline: Vitor's Blog and code index
email: mussatto@gmail.com
description: VM Blog and reference code repository. This is a space to share a little bit of code that might help others.
baseurl: ""
url: "http://mussatto.github.io"
twitter_username: vitormussatto
github_username:  mussatto
linkedin_page: vitormussatto

# Build settings
highlighter: rouge
paginate: 10
plugins: [jekyll-paginate, jekyll-watch, jekyll-sitemap,jekyll-seo-tag]
