# Site settings
title: VM Blog
email: mussatto@gmail.com
description: A software development blog about java, golang and development with tutorials. Written by Vitor Mussatto
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mussatto.github.io" # the base hostname & protocol for your site
twitter_username: vitormussatto
github_username:  mussatto
linkedin_page: vitormussatto

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
gems: [jekyll-paginate,jekyll-coffeescript, jekyll-watch, jekyll-assets,jekyll-sitemap,jekyll-seo-tag]
