# Site settings
title: VM Blog
email: mussatto@gmail.com
description: Vitor Mussatto's Blog
baseurl: ""
url: "http://mussatto.github.io"
twitter_username: vitormussatto
github_username:  mussatto
linkedin_page: vitormussatto

# Build settings
highlighter: rouge
paginate: 10
plugins: [jekyll-paginate, jekyll-watch, jekyll-sitemap,jekyll-seo-tag]
